### ISSUE TITLE
Express app stops responding if there are too many partial includes

### ISSUE THREAD

**Issue by nerdgore** [krakenjs/makara#69] opened 2015-07-29 15:37 UTC
It seems that makara does something strange that causes an express app to become unresponsive if multiple partial includes are used.

A sample app to illustrate this behaviour can be found in my github.
[makara-bug](https://github.com/nerdgore/makara-bug)

As far as I can tell this doesn't relate to adaro since the partials get resolved correctly. However the render function never finishes and the app just hangs without throwing any error.

**Comment by grawk** [comment] 2015-07-29 15:51
Thanks for the illustration app! That's going to help a lot in debugging and fixing this issue :)

**Comment by brakon** [comment] 2015-07-29 18:27
I'm having an issue when under heavy load a kraken app will just hang on any further requests, it doesn't even get to call the adaro engine js read mechanism, wonder if its related or how I can tell if its a similar problem.

**Comment by grawk** [comment] 2015-07-29 18:34
@brakon Can you please try and trace it as far as you can into the code (given your time constraints etc) and file an issue on the appropriate repository? If you aren't able to assess the exact repo, please file an issue on the krakenjs repository with as much info as you can gather. Then we can help you drill down and find the problem.

**Comment by grawk** [comment] 2015-09-25 19:42
Hi @nerdgore. I cloned your app. I do see the hanging behavior you mentioned. I've yet to debug it but I noted that by switching "cache" to true, I can avoid it.

I will update you as I get more results.

**Comment by grawk** [comment] 2015-09-26 22:26
Well. I found the problem.. Spent a couple hours looking. After finding the problem, I discovered it actually has been resolved already by @aredridel !!

`engine-munger` had a bug which allowed the `numPendingStats` variable to run away. It was resolved here:
https://github.com/krakenjs/engine-munger/commit/467e09e082d71545fab9d2d90cfcf6a55b591aba

If you update your `makara` dependency to pick up the latest patch version (`2.0.3`) you will find that the issue is resolved!

@brakon can you try the same? I am closing this issue.

**Closed as completed by grawk** 2015-09-26 22:26 UTC

**Comment by brakon** [comment] 2015-09-28 19:29
yes this works for me :+1:  I am the one who created the ticket with the details :P
https://github.com/krakenjs/engine-munger/issues/37
